#!/usr/bin/env python

class RoomEnum(object):
    HALL = 1
    LOUNGE = 2
    DINING_ROOM = 3
    KITCHEN = 4
    BALLROOM = 5
    CONSERVATORY = 6
    BILLIARD_ROOM = 7
    LIBRARY = 8
    STUDY = 9
    HALLWAY_HALL_LOUNGE = 10
    HALLWAY_LOUNGE_DINING = 11
    HALLWAY_DINING_KITCHEN = 12
    HALLWAY_KITCHEN_BALLROOM = 13
    HALLWAY_BALLROOM_CONSERV = 14
    HALLWAY_CONSERV_BILLIARD = 15
    HALLWAY_BILLIARD_LIBRARY = 16
    HALLWAY_LIBRARY_STUDY = 17
    HALLWAY_STUDY_HALL = 18