#!/usr/bin/env python

class RoomEnum(object):
    STUDY = 1
    HALL = 2
    LOUNGE = 3
    DINING_ROOM = 4
    KITCHEN = 5
    BALLROOM = 6
    CONSERVATORY = 7
    LIBRARY = 8
    BILLIARD_ROOM = 9
    HALLWAY_STUDY_HALL = 10
    HALLWAY_HALL_LOUNGE = 11
    HALLWAY_LOUNGE_DINING_ROOM = 12
    HALLWAY_DINING_ROOM_KITCHEN = 13
    HALLWAY_KITCHEN_BALLROOM = 14
    HALLWAY_BALLROOM_CONSERVATORY = 15
    HALLWAY_CONSERVATORY_LIBRARY = 16
    HALLWAY_LIBRARY_STUDY = 17
    HALLWAY_BILLIARD_ROOM_HALL = 18
    HALLWAY_BILLIARD_ROOM_DINING_ROOM = 19
    HALLWAY_BILLIARD_ROOM_BALLROOM = 20
    HALLWAY_BILLIARD_ROOM_LIBRARY = 21